# Uncomment the next line to define a global platform for your project
platform :osx, '11.6'

target 'Graphs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Graphs

  target 'GraphsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Sourcery'
  end

end
